//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSERT_PROCEDURE_WEBABI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeEntity : DbContext
    {
        public EmployeeEntity()
            : base("name=EmployeeEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TABLE_EMPLOYEE> TABLE_EMPLOYEE { get; set; }
    
        public virtual int PROC_EMP(string name, string surname, string age, string mail)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            var ageParameter = age != null ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_EMP", nameParameter, surnameParameter, ageParameter, mailParameter);
        }
    
        public virtual ObjectResult<PROC_EMPLOYEE_SELECT_Result> PROC_EMPLOYEE_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_EMPLOYEE_SELECT_Result>("PROC_EMPLOYEE_SELECT");
        }
    }
}
